(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.jumpstate = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";function addAction(t,e){Actions[t]=function(t){return e(t)}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.addAction=addAction;var Actions={};exports.default=Actions;

},{}],2:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.EffectRegistry=void 0,exports.default=function(){var e=arguments.length>1,t=arguments.length<=0?void 0:arguments[0],r=e?arguments.length<=1?void 0:arguments[1]:arguments.length<=0?void 0:arguments[0];if(e&&"string"!=typeof t)throw new Error('Named Jumpsuit effects require a string as the name eg. Effect("MY_ACTION", () => {...})');var i=function(i){if(e){if(t!==i.type)return;return r(i.payload,_middleware.getState,_middleware.dispatch)}return r(i,_middleware.getState,_middleware.dispatch)};if(EffectRegistry.push(i),e){var a=function(){for(var e=arguments.length,r=Array(e),i=0;i<e;i++)r[i]=arguments[i];return(0,_middleware.dispatch)({type:t,payload:r})};return(0,_actions.addAction)(t,a),a}};var _middleware=require("./middleware"),_actions=require("./actions"),EffectRegistry=exports.EffectRegistry=[];

},{"./actions":1,"./middleware":4}],3:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.dispatch=exports.getState=exports.CreateJumpstateMiddleware=exports.StateDefaults=exports.Actions=exports.Effect=exports.State=void 0;var _state=require("./state"),_state2=_interopRequireDefault(_state),_effect=require("./effect"),_effect2=_interopRequireDefault(_effect),_actions=require("./actions"),_actions2=_interopRequireDefault(_actions),_middleware=require("./middleware"),_middleware2=_interopRequireDefault(_middleware);exports.State=_state2.default,exports.Effect=_effect2.default,exports.Actions=_actions2.default,exports.StateDefaults=_state.StateDefaults,exports.CreateJumpstateMiddleware=_middleware2.default,exports.getState=_middleware.getState,exports.dispatch=_middleware.dispatch;
},{"./actions":1,"./effect":2,"./middleware":4,"./state":5}],4:[function(require,module,exports){
"use strict";function createMiddleware(t){return function(t){return dispatch===warningFn&&(exports.dispatch=dispatch=t.dispatch,exports.getState=getState=t.getState),function(t){return function(e){var r=t(e);return _effect.EffectRegistry.forEach(function(t){return t(e)}),r}}}}Object.defineProperty(exports,"__esModule",{value:!0}),exports.getState=exports.dispatch=void 0,exports.default=createMiddleware;var _effect=require("./effect"),warningFn=function(){console.warn("It looks like you're trying to use Jumpstate without the middleware! For Jumpstate to work, you need to run CreateJumpstateMiddleware() and apply it as middleware to your Redux Store.")},dispatch=exports.dispatch=warningFn,getState=exports.getState=warningFn;

},{"./effect":2}],5:[function(require,module,exports){
(function (process){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.StateDefaults=void 0,exports.default=function(){var e=arguments.length>1,t=e?arguments.length<=0?void 0:arguments[0]:{},a=e?arguments.length<=1?void 0:arguments[1]:arguments.length<=0?void 0:arguments[0];"string"==typeof t&&(t={name:t});var n=void 0;t.name&&(n=t.name.split(""),n=n[0].toUpperCase()+n.slice(1).join(""));var i=Object.assign({},StateDefaults,t);if("string"==typeof i.name&&!i.name.length)throw new Error("States require a name when defined with a config");var r=a.initial;delete a.initial;var o={},s=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:r,t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:{};if(!t)return e;if(o[t.type]){var a=o[t.type](e,t.payload);return i.autoAssign?Object.assign({},e,a):a}return e};return Object.keys(a).forEach(function(e){var t=n?i.name+"_"+e:e;o[t]=a[e];var r=function(e){var a={type:t,payload:e};return(0,_middleware.dispatch)(a)};s[e]=r,(0,_actions.addAction)(e,r),"undefined"!=typeof process&&"testing"===process.env.NODE_ENV&&(s["_"+e]=a[e])}),s};var _middleware=require("./middleware"),_actions=require("./actions"),StateDefaults=exports.StateDefaults={autoAssign:!0};
}).call(this,require('_process'))
},{"./actions":1,"./middleware":4,"_process":6}],6:[function(require,module,exports){
function defaultSetTimout(){throw new Error("setTimeout has not been defined")}function defaultClearTimeout(){throw new Error("clearTimeout has not been defined")}function runTimeout(e){if(cachedSetTimeout===setTimeout)return setTimeout(e,0);if((cachedSetTimeout===defaultSetTimout||!cachedSetTimeout)&&setTimeout)return cachedSetTimeout=setTimeout,setTimeout(e,0);try{return cachedSetTimeout(e,0)}catch(t){try{return cachedSetTimeout.call(null,e,0)}catch(t){return cachedSetTimeout.call(this,e,0)}}}function runClearTimeout(e){if(cachedClearTimeout===clearTimeout)return clearTimeout(e);if((cachedClearTimeout===defaultClearTimeout||!cachedClearTimeout)&&clearTimeout)return cachedClearTimeout=clearTimeout,clearTimeout(e);try{return cachedClearTimeout(e)}catch(t){try{return cachedClearTimeout.call(null,e)}catch(t){return cachedClearTimeout.call(this,e)}}}function cleanUpNextTick(){draining&&currentQueue&&(draining=!1,currentQueue.length?queue=currentQueue.concat(queue):queueIndex=-1,queue.length&&drainQueue())}function drainQueue(){if(!draining){var e=runTimeout(cleanUpNextTick);draining=!0;for(var t=queue.length;t;){for(currentQueue=queue,queue=[];++queueIndex<t;)currentQueue&&currentQueue[queueIndex].run();queueIndex=-1,t=queue.length}currentQueue=null,draining=!1,runClearTimeout(e)}}function Item(e,t){this.fun=e,this.array=t}function noop(){}var process=module.exports={},cachedSetTimeout,cachedClearTimeout;!function(){try{cachedSetTimeout="function"==typeof setTimeout?setTimeout:defaultSetTimout}catch(e){cachedSetTimeout=defaultSetTimout}try{cachedClearTimeout="function"==typeof clearTimeout?clearTimeout:defaultClearTimeout}catch(e){cachedClearTimeout=defaultClearTimeout}}();var queue=[],draining=!1,currentQueue,queueIndex=-1;process.nextTick=function(e){var t=new Array(arguments.length-1);if(arguments.length>1)for(var u=1;u<arguments.length;u++)t[u-1]=arguments[u];queue.push(new Item(e,t)),1!==queue.length||draining||runTimeout(drainQueue)},Item.prototype.run=function(){this.fun.apply(null,this.array)},process.title="browser",process.browser=!0,process.env={},process.argv=[],process.version="",process.versions={},process.on=noop,process.addListener=noop,process.once=noop,process.off=noop,process.removeListener=noop,process.removeAllListeners=noop,process.emit=noop,process.binding=function(e){throw new Error("process.binding is not supported")},process.cwd=function(){return"/"},process.chdir=function(e){throw new Error("process.chdir is not supported")},process.umask=function(){return 0};
},{}]},{},[3])(3)
});